
server:
  port: 9005
spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/account
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
